#!/bin/bash

IMAGE_NAME=${IMAGE_NAME:-rpi.img}

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

cleanup() {
   if [[ -d "mnt" ]]; then
        umount "mnt/dev" || true
        umount "mnt/proc" || true
        umount "mnt/sys" || true
        umount "mnt/boot" || true
        umount "mnt" || true
        rmdir "mnt" || true
   fi

   loopdev=$(losetup --find --show "${IMAGE_NAME}")
   [ -n "${loopdev}" ] && losetup --detach "${loopdev}" || true
}

trap cleanup EXIT

disk-init
load-os

# run custom setup script inside context of image
if [[ -f "/tmp/setup" ]]; then
  install -Dm755 "/tmp/setup" "mnt/tmp/setup"
  chroot mnt "/tmp/setup"
fi

# now export the finalized image for flashing
cp "${IMAGE_NAME}" "/tmp/${IMAGE_NAME}"

echo "---------------------------------------------"
echo " ${IMAGE_NAME} is now ready for flashing"
echo "---------------------------------------------"
