#!/bin/bash

# modify this to meet your needs on the Raspberry Pi device
echo "customizing device..." 

# install some software copied from shared volume...
if [[ -n "${SCRIPT_DIR}" ]]; then
    "${SCRIPT_DIR}/test-script"
fi